version: 2.19.11

orbs:
  node: circleci/node@4.1.0

jobs:

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Giving permissions
          command: chmod +x mvnw
      - run:   
          command: ./mvnw -Dmaven.test.skip=true package

  test-1:
    docker:
      - image: circleci/openjdk:stretch
    steps:
     - checkout
     - run:
        name: Giving permissions
        command: chmod +x mvnw
     - run:
        command: ./mvnw test

workflows:
  version: 2.19.11
  build-test:
    jobs:
      - build
      - test-1:
          requires:
            - build













